AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/Documentation:
  Enabled: false  # Disables the documentation requirement for classes

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'  # Don't be too strict with test file lengths 